/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info5100.university.jframe;

/**
 *
 * @author amishagupta
 */
public class FeedBackPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedBackPanel
     */
    public FeedBackPanel() {
        initComponents();
           Course_Name1.setText("PSA 4352");
           Course_Name2.setText("Web Design 6120");
           Course_Name3.setText("AED 5100");
           Course_Name4.setText("DMDD 1000");
           txtGPA.setText("3.7");
           txtName.setText("Chandler");
           txtDepartment.setText("Information Systems");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblheading = new javax.swing.JLabel();
        LayeredPane_studentdetails = new javax.swing.JLayeredPane();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGPA = new javax.swing.JLabel();
        txtGPA = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        LayeredPane_Feedback = new javax.swing.JLayeredPane();
        ComboBox_Course3 = new javax.swing.JComboBox<>();
        Course_Name2 = new javax.swing.JTextField();
        ComboBox_Course1 = new javax.swing.JComboBox<>();
        Course_Name4 = new javax.swing.JTextField();
        Course_Name1 = new javax.swing.JTextField();
        ComboBox_Course2 = new javax.swing.JComboBox<>();
        ComboBox_Course4 = new javax.swing.JComboBox<>();
        Course_Name3 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        lblheading.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblheading.setText("       FEEDBACK FORM");

        LayeredPane_studentdetails.setBackground(new java.awt.Color(114, 110, 110));
        LayeredPane_studentdetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 13)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        LayeredPane_studentdetails.setToolTipText("");

        lblName.setText("Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblGPA.setText("GPA");

        lblDepartment.setText("Department");

        LayeredPane_studentdetails.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_studentdetails.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_studentdetails.setLayer(lblGPA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_studentdetails.setLayer(txtGPA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_studentdetails.setLayer(txtDepartment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_studentdetails.setLayer(lblDepartment, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPane_studentdetailsLayout = new javax.swing.GroupLayout(LayeredPane_studentdetails);
        LayeredPane_studentdetails.setLayout(LayeredPane_studentdetailsLayout);
        LayeredPane_studentdetailsLayout.setHorizontalGroup(
            LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPane_studentdetailsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGPA)
                    .addComponent(lblName)
                    .addComponent(lblDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        LayeredPane_studentdetailsLayout.setVerticalGroup(
            LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPane_studentdetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPA)
                    .addComponent(txtGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LayeredPane_studentdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LayeredPane_Feedback.setBackground(new java.awt.Color(114, 110, 110));
        LayeredPane_Feedback.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feedback", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 1, 13)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        ComboBox_Course3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bad", "Good", "Very Good", "Excellent" }));
        ComboBox_Course3.setSelectedIndex(1);
        ComboBox_Course3.setToolTipText("Rating");

        ComboBox_Course1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bad", "Good", "Very Good", "Excellent" }));
        ComboBox_Course1.setSelectedIndex(1);
        ComboBox_Course1.setToolTipText("Rating");
        ComboBox_Course1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Course1ActionPerformed(evt);
            }
        });

        Course_Name4.setToolTipText("");
        Course_Name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_Name4ActionPerformed(evt);
            }
        });

        Course_Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Course_Name1ActionPerformed(evt);
            }
        });

        ComboBox_Course2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bad", "Good", "Very Good", "Excellent" }));
        ComboBox_Course2.setSelectedIndex(1);
        ComboBox_Course2.setToolTipText("Rating");
        ComboBox_Course2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Course2ActionPerformed(evt);
            }
        });

        ComboBox_Course4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bad", "Good", "Very Good", "Excellent" }));
        ComboBox_Course4.setSelectedIndex(1);
        ComboBox_Course4.setToolTipText("Rating");

        LayeredPane_Feedback.setLayer(ComboBox_Course3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(Course_Name2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(ComboBox_Course1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(Course_Name4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(Course_Name1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(ComboBox_Course2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(ComboBox_Course4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPane_Feedback.setLayer(Course_Name3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPane_FeedbackLayout = new javax.swing.GroupLayout(LayeredPane_Feedback);
        LayeredPane_Feedback.setLayout(LayeredPane_FeedbackLayout);
        LayeredPane_FeedbackLayout.setHorizontalGroup(
            LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPane_FeedbackLayout.createSequentialGroup()
                .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayeredPane_FeedbackLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Course_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredPane_FeedbackLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Course_Name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Course_Name3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Course_Name4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayeredPane_FeedbackLayout.createSequentialGroup()
                        .addComponent(ComboBox_Course1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(LayeredPane_FeedbackLayout.createSequentialGroup()
                        .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Course2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_Course3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_Course4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        LayeredPane_FeedbackLayout.setVerticalGroup(
            LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPane_FeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Course1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Course2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course_Name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Course3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LayeredPane_FeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course_Name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Course4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(LayeredPane_studentdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LayeredPane_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LayeredPane_studentdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LayeredPane_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void ComboBox_Course1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Course1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_Course1ActionPerformed

    private void ComboBox_Course2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Course2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_Course2ActionPerformed

    private void Course_Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_Name1ActionPerformed
     
    }//GEN-LAST:event_Course_Name1ActionPerformed

    private void Course_Name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Course_Name4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Course_Name4ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Course1;
    private javax.swing.JComboBox<String> ComboBox_Course2;
    private javax.swing.JComboBox<String> ComboBox_Course3;
    private javax.swing.JComboBox<String> ComboBox_Course4;
    private javax.swing.JTextField Course_Name1;
    private javax.swing.JTextField Course_Name2;
    private javax.swing.JTextField Course_Name3;
    private javax.swing.JTextField Course_Name4;
    private javax.swing.JLayeredPane LayeredPane_Feedback;
    private javax.swing.JLayeredPane LayeredPane_studentdetails;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblheading;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
